model: lstm # resnet, cnn, lstm, autoencoder
data_source: arp # m4, airpassengers, sine_data, arp
number_of_nodes: 64
number_of_epochs: 1000
number_of_mc_forward_passes: 20 # Number of forward passes done to obtain Bayesian estimate of output
batch_size: 32
dropout_rate: 0.4
sequence_length: 24 # Length of sequence used as input when predicting next step
forecasting_horizon: 1
test_size: 0.2 # Fraction of data set used for testing
multi_step_prediction: True # True / False if using predicted values to predict further or using actual test data
differencing: True # If True, differences the data before fitting model, and then inverse it afterwards
mc_dropout: True # If True, Dropout is applied at testing phase, in order to get an mc estimate of prediction interval