model: cnn # resnet, cnn, lstm, autoencoder
data_source: airpassengers # m4, airpassengers, sine_data
number_of_nodes: 32
number_of_epochs: 200
batch_size: 32
dropout_rate: 0.4
sequence_length: 24
forecasting_horizon: 1
test_size: 0.2 # Percentage

