model: lstm # resnet, cnn, lstm, cnn_lstm_encoder
data_source: avocado # m4, airpassengers, sine_data, arp, trend_seasonal, avocado
number_of_nodes: 50
number_of_epochs: 30
number_of_mc_forward_passes: 100 # Number of forward passes done to obtain Bayesian estimate of output
batch_size: 128
dropout_rate_test: 0.5 # Dropout_rate during testing
patience: 10
sequence_length: 4 # Length of sequence used as input when predicting next step
forecasting_horizon: 1 # Number of steps in the future predicted
test_size: 0.4 # Fraction of data set used for testing
multi_step_prediction: False # True / False if using predicted values to predict further or using actual test data
differencing: False # If True, differences the data before fitting model, and then inverse it afterwards
mc_dropout: True # If True, Dropout is applied at testing phase, in order to get an mc estimate of prediction interval
autoencoder: lstm
load_weights_autoencoder: False