data_source: avocado
data_path: 'C://Users//mathi//PycharmProjects//timeseries_uncertainty//data//raw//'

sequence_length: 24 # Length of sequence used as input when predicting next step
forecast_horizon: 12 # Number of steps in the future to predict when using sliding window
validation_size: 0.1 # Fraction of data set used for validation
test_size: 0.2 # Fraction of data set used for testing
multi_step_prediction: True # True / False if using predicted values to predict further or using actual test data
number_of_mc_forward_passes: 500 # Number of forward passes done to obtain Bayesian estimate of output
dropout_rate_test: 0.4 # Dropout_rate during testing
use_general_model: False

general_model:
  model: rnn # rnn, lstm, cnn
  rnn_hyperparameters:
    model: RNN
    number_of_nodes: 64
    number_of_epochs: 300
    batch_size: 64
    learning_rate: 0.001
    dropout_rate: 0.4
    number_of_layers: 3

  lstm_hyperparameters:
    model: LSTM
    number_of_nodes: 64
    number_of_epochs: 300
    batch_size: 64
    learning_rate: 0.001
    dropout_rate: 0.4
    number_of_layers: 3

  cnn_hyperparameters:
    model: CNN
    number_of_nodes: 64
    number_of_epochs: 300
    batch_size: 32
    learning_rate: 0.001
    dropout_rate: 0.4
    number_of_layers: 3

specific_model:
  model: rnn # rnn, lstm, cnn
  rnn_hyperparameters:
    model: RNN
    number_of_nodes: 64
    number_of_epochs: 20
    batch_size: 64
    learning_rate: 0.001
    dropout_rate: 0.4
    number_of_layers: 1

  lstm_hyperparameters:
    model: LSTM
    number_of_nodes: 64
    number_of_epochs: 50
    batch_size: 64
    learning_rate: 0.001
    dropout_rate: 0.4
    number_of_layers: 1

  cnn_hyperparameters:
    model: CNN
    number_of_nodes: 64
    number_of_epochs: 60
    batch_size: 32
    learning_rate: 0.001
    dropout_rate: 0.4
    number_of_layers: 1
