model: rnn # rnn, lstm, cnn
data_source: airpassengers # m4, airpassengers, avocado, oslo, gunpoint
data_path: 'C://Users//mathi//PycharmProjects//timeseries_uncertainty//data//raw//'
number_of_nodes: 64
number_of_epochs: 200
number_of_mc_forward_passes: 500 # Number of forward passes done to obtain Bayesian estimate of output
batch_size: 64
dropout_rate_test: 1 # Dropout_rate during testing
patience: 1000
sequence_length: 24 # Length of sequence used as input when predicting next step
forecast_horizon: 12 # Number of steps in the future to predict when using sliding window
forecasting_horizon: 1 # This is old, and should be set to 1
validation_size: 0.1 # Fraction of data set used for validation
test_size: 0.2 # Fraction of data set used for testing
multi_step_prediction: True # True / False if using predicted values to predict further or using actual test data
differencing: 0 # If True, differences the data before fitting model, and then inverse it afterwards
mc_dropout: True # If True, Dropout is applied at testing phase, in order to get an mc estimate of prediction interval
autoencoder: 0
load_weights_autoencoder: False
external_features: False